linkedList: test.o CircularList.o Wrapper.o
	g++ -o linkedList test.o CircularList.o Wrapper.o

Wrapper.o: Wrapper.cpp Wrapper.h CircularList.h
		g++ -c -O3 -Wall -std=c++14 Wrapper.cpp

CircularList.o: CircularList.h CircularList.cpp
		gcc -c -O3 -Wall -std=c++14 CircularList.cpp

test.o: test.c Wrapper.h
		gcc -c -O3 -Wall test.c

clean:
		rm -f *.o linkedList
